### ISSUE TITLE
Server timing spec compliance

### ISSUE THREAD

**Issue by motss** [lolo32/fastify-response-time#1]
Is it possible to make this to be a Server timing thing since it does something quite similar?

**Comment by lolo32** [comment]
I do not understand what you want me to implement. Could you explain what is `Server timing thing`?

If you prefer, I made another plugin that allow you to change heanders just before there are sent.  Have a look at [fastify-onheader](/lolo32/fastify-onheader#readme)

**Comment by millette** [comment]
I guess @motss meant https://www.w3.org/TR/server-timing/

**Comment by lolo32** [comment]
OK, I will read it later this night.

Thanks @millette
